[project]
name = "blend-view"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
bv = "bv.main:run"

[tool.setuptools]
packages  = ["bv"]

[tool.setuptools.package-data]
bv = ["data/*"]
